services:
  rinhadebackend-api-1: &api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "125MB"

  rinhadebackend-api-2:
    <<: *api

  nginx:
    image: nginx:1.27.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - backend
    depends_on:
      - rinhadebackend-api-1
      - rinhadebackend-api-2
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
  