services:
  rinhadebackend-api-1: &api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Shared volume for Unix socket
      - unix-sockets:/tmp
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      - processed-payments-api  # Wait for socket creator to start
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"
          
  rinhadebackend-api-2:
    <<: *api
    
  processed-payments-api:
    build:
      context: .
      dockerfile: ProcessedPayments.API/Dockerfile
    volumes:
      # Same shared volume - this container creates the socket
      - unix-sockets:/tmp
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"
      
  nginx:
    image: nginx:1.27.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - backend
    depends_on:
      - rinhadebackend-api-1
      - rinhadebackend-api-2
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
          
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

# Named volume that will be shared between containers
volumes:
  unix-sockets:
    driver: local